stages:
- build

build-image:
  image: jdrouet/docker-with-buildx:20
  stage: build
  only:
  - tags
  services:
  - docker:20-dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker buildx create --use
  - docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE:latest --push .
